### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by anukaal**
updated classifiers with python 3.8 and 3.9

### CODE REVIEW

**Comment by Jinyu-W** [comment]
Hi @anukaal, may I know why do you want to upgrade the python version?

**Comment by anukaal** [comment]
> Hi @anukaal, may I know why do you want to upgrade the python version?

To be updated with the new version of python !

**Comment by Jinyu-W** [comment]
closed since we have PR #398

**Comment by Jinyu-W** [comment]
> !

Sorry, do you mean that you want to further enhance this PR?

**Pull request closed without merging**
