### PR TITLE
package version updated with several bug fix, refinement, new example

### PR DESCRIPTION
**Pull request by Jinyu-W**
# Description

This PR contains several PRs including some bug fix, new example addition, doc addition and refinement, new features, new tests. The package version is also updated from 0.1.1a11 to 0.1.2a0.

## Linked issue(s)/Pull request(s)

- [138](https://github.com/microsoft/maro/pull/138):
  - refine data push/pull in cli
- [112](https://github.com/microsoft/maro/pull/112):
  - add fall back function in weather download
- [136](https://github.com/microsoft/maro/pull/136):
  - add docs for example
- [144](https://github.com/microsoft/maro/pull/144):
  - switching the key and values of the handler dict which is used in the dist decorator
  - add unit tests for the dist decorator
  - fixed the multithreading deadlock in the maro unit test suite
- [147](https://github.com/microsoft/maro/pull/147):
  - remove useless reward() from Env, BE, yaml config
  - refine the format & style for core & BE
- [157](https://github.com/microsoft/maro/pull/157):
  - add docs for AzCopy
  - add dqn tests in grass/k8s mode
- [160](https://github.com/microsoft/maro/pull/160), [164](https://github.com/microsoft/maro/pull/164):
  - fix the data generation description for citi bike in docs
- [60](https://github.com/microsoft/maro/pull/60):
  - add example/cim/gnn
- [166](https://github.com/microsoft/maro/pull/166):
  - fix the uppicklable bug in RL toolkit store
- [167](https://github.com/microsoft/maro/pull/167):
  - rename the confusing components in RL toolkit and example/cim/dqn

## Type of Change

- [x] Non-breaking bug fix
- [ ] Breaking bug fix
- [x] New feature
- [x] Test
- [x] Doc update
- [ ] Docker update

## Related Component

- [x] Simulation toolkit
- [x] RL toolkit
- [x] Distributed toolkit

## Has Been Tested

- OS:
  - [x] Windows
  - [x] Mac OS
  - [x] Linux
- Python version:
  - [x] 3.6
  - [ ] 3.7
- Key information snapshot(s):
  
## Needs Follow Up Actions

- [x] New release package
- [x] New docker image

## Checklist

- [ ] Add/update the related comments
- [ ] Add/update the related tests
- [ ] Add/update the related documentations
- [ ] Update the dependent downstream modules usage

### CODE REVIEW

**Comment by ArthurJiang** [comment]
Add the description for details.

**Comment by ArthurJiang** [comment]
change a meaningful title

**Comment by ArthurJiang** [comment]
update version to 0.1.1a12 in maro/__misc__.py

**Comment by Jinyu-W** [comment]
> Add the description for details.

done

**Comment by Jinyu-W** [comment]
> update version to 0.1.2a0 in maro/**misc**.py

done

**Comment by Jinyu-W** [comment]
> change a meaningful title

done

**Review by ArthurJiang — APPROVED** [review]

**Pull request merged**
